language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_script: composer -n --prefer-source install --dev

script: vendor/bin/phpunit --coverage-clover clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover
